# Generated by Django 2.1.1 on 2018-09-11 04:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False)),
                ('reward', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rewards.Reward')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('street_address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='rewards.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='expires_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 4, 26, 12, 176575)),
        ),
        migrations.AlterField(
            model_name='task',
            name='reward',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rewards.Reward'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rewards.Status'),
        ),
        migrations.AddField(
            model_name='payment',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rewards.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rewards.School'),
        ),
    ]
